---
- name: Upgrading System Packages
  become: yes
  apt: 
    update_cache: yes
    upgrade: dist
    autoclean: yes
    

- name: Installing Utility Packages
  apt: 
    name: "{{server.packages}}"
    only_upgrade: yes
    state: latest

- name: Setting timezone
  timezone:
    name: "{{server.timezone}}"

- name: Set default locale
  shell: localectl set-locale LANG={{server.locale}}

- name: Add ondrej PHP Repo
  apt_repository: 
    repo: ppa:ondrej/php
    state: present

- name: Set the hostname in /etc/hostname
  shell: echo {{ server.hostname }} > /etc/hostname
  when: server.hostname is defined

- name: Set the hostname
  shell: hostname {{ server.hostname }}
  when: server.hostname is defined

- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ server.hostname }}' owner=root group=root mode=0644